name: Unit Tests

on: [push, pull_request]

env:
  RELEASE: 0
  artifact: 0

jobs:
  macos_test:
    name: macOS [${{ matrix.BACKEND }}]
    strategy:
      fail-fast: false
      matrix:
        BACKEND: [lmdb, rocksdb]
        RELEASE:
          - ${{ startsWith(github.ref, 'refs/tags/') }}
    env:
      BOOST_ROOT: /tmp/boost
      BACKEND: ${{ matrix.BACKEND }}
      TEST_USE_ROCKSDB: ${{ matrix.BACKEND == 'rocksdb' && '1' || '0' }}
      RELEASE: ${{ matrix.RELEASE }}
    runs-on: macos-12
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0 # needed for restore-git-mtimes

      - name: Restore Timestamps
        uses: ./.github/actions/restore-git-mtimes

      - name: Cache Build
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: build
          key: ${{ runner.os }}-build-cache

      - name: Fetch Deps
        run: TEST=1 ci/actions/osx/install_deps.sh

      - name: Build Tests
        run: ci/build-ci.sh "/tmp/qt/lib/cmake/Qt5";

      - name: Run Tests [TEST_USE_ROCKSDB=${{ env.TEST_USE_ROCKSDB }}]
        run: cd build && sudo TEST_USE_ROCKSDB=$TEST_USE_ROCKSDB ../ci/test.sh .
        env:
          DEADLINE_SCALE_FACTOR: ${{ env.TEST_USE_ROCKSDB == 1 && '2' || '1' }}

  linux_test:
    name: Linux [${{ matrix.BACKEND }}-${{ matrix.COMPILER }}]
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        BACKEND: [lmdb, rocksdb]
        COMPILER: [gcc, clang]
        RELEASE:
          - ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-22.04
    env:
      COMPILER: ${{ matrix.COMPILER }}
      BACKEND: ${{ matrix.BACKEND }}
      TEST_USE_ROCKSDB: ${{ matrix.BACKEND == 'rocksdb' && '1' || '0' }}
      RELEASE: ${{ matrix.RELEASE }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0 # needed for restore-git-mtimes

      - name: Restore Timestamps
        uses: ./.github/actions/restore-git-mtimes

      - name: Fetch Deps
        run: ci/actions/linux/install_deps.sh

      - name: Cache Build
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: build
          key: ${{ runner.os }}-${{ env.COMPILER }}-build-cache

      - name: Build Tests
        run: docker run -e TEST_USE_ROCKSDB -e RELEASE -v ${PWD}:/workspace nanocurrency/nano-env:${{ matrix.COMPILER }} /bin/bash -c "cd /workspace && ./ci/build-ci.sh /usr/lib/x86_64-linux-gnu/cmake/Qt5"

      - name: Run Tests [TEST_USE_ROCKSDB=${{ env.TEST_USE_ROCKSDB }}]
        run: docker run -e RELEASE -e TEST_USE_ROCKSDB -e DEADLINE_SCALE_FACTOR -v ${PWD}:/workspace nanocurrency/nano-env:${{ matrix.COMPILER }} /bin/bash -c "cd /workspace/build && ../ci/test.sh ."
        env:
          DEADLINE_SCALE_FACTOR: ${{ env.TEST_USE_ROCKSDB == 1 && '2' || '1' }}

  windows_test:
    name: Windows [${{ matrix.BACKEND }}]
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        BACKEND: [lmdb, rocksdb]
        RELEASE:
          - ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: windows-latest
    env:
      BACKEND: ${{ matrix.BACKEND }}
      TEST_USE_ROCKSDB: ${{ matrix.BACKEND == 'rocksdb' && '1' || '0' }}
      RELEASE: ${{ matrix.RELEASE }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0 # needed for restore-git-mtimes

      - name: Restore Timestamps
        uses: ./.github/actions/restore-git-mtimes

      - name: Cache Build
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: build
          key: ${{ runner.os }}-build-cache

      - name: Windows Defender
        run: ci/actions/windows/disable_windows_defender.ps1

      - name: Fetch Deps
        run: ci/actions/windows/install_deps.ps1

      - name: Build Tests
        run: ci/actions/windows/build.ps1

      - name: Run Tests [TEST_USE_ROCKSDB=${{ env.TEST_USE_ROCKSDB }}]
        run: cd build && ../ci/actions/windows/test.ps1
        env:
          DEADLINE_SCALE_FACTOR: ${{ env.TEST_USE_ROCKSDB == 1 && '2' || '1' }}

      # - name: Run Tests lmdb
      #   if: ${{ env.TEST_USE_ROCKSDB == 0 }}
      #   run: ci/actions/windows/build.ps1
      # - name: Run Tests rocksdb
      #   if: ${{ env.TEST_USE_ROCKSDB == 1 }}
      #   env:
      #     DEADLINE_SCALE_FACTOR: 2
      #   run: ci/actions/windows/build.ps1
